# Generated by Django 4.0.5 on 2022-06-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_imagem',
            field=models.CharField(default='https://2.bp.blogspot.com/-D1dooVSafi4/V9vwv4fEYYI/AAAAAAABFQU/GgOCoa6c6OsnRyLFZJY-m9Dax59ZZAPOwCEw/s640/burrito.jpg', max_length=500),
        ),
    ]
